# -*- coding: utf-8 -*-
"""Wholesale customers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JRsYcU9BP-vFCspab-NhjoLJcrBGYgmx

# Plot the original points
"""

x=[4,5,10,4,3,11,14,6,10,12]
y=[21,19,24,17,16,25,24,22,21,21]

import matplotlib.pyplot as plt
for i in range(len(x)):
  plt.plot(x[i],y[i],marker='o',color='b')
  plt.text(x[i],y[i]-0.4,s=f"{i+1}")
plt.show()

"""# Create clusters"""

data=list(zip(x,y))
from sklearn.cluster import KMeans
kmeans=KMeans(n_clusters=3)
kmeans.fit(data)
classes=[int(c) for c in kmeans.labels_]
print(classes)

"""# Plot with auto colors"""

plt.scatter(x,y,c=classes)
plt.show()

"""#Elbow method"""

print(kmeans.inertia_)

inertias=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i)
  kmeans.fit(data)
  inertias.append(kmeans.inertia_)
plt.plot(range(1,11),inertias,marker='o')
plt.show()

"""# Reset kmeans back to 3 clusters"""

kmeans=KMeans(n_clusters=3)
kmeans.fit(data)

"""# Plot with manual colors and labels"""

colors=['red','blue','green']
for i in range(len(x)):
  plt.plot(x[i],y[i],marker='o',color=colors[classes[i]])
  plt.text(x[i],y[i]-0.4,s=f"{i+1}")
plt.show()

"""# Predict new point with KMeans"""

new_x=100
new_y=20
new_point=[(new_x,new_y)]
prediction=kmeans.predict(new_point)
print(f"The new point belongs to class {prediction[0]}")
plt.scatter(x+[new_x],y+[new_y],c=classes+[int(prediction[0])])
plt.text(new_x,new_y-0.4,s=f"new point:class={prediction[0]}")
plt.show()

"""#Predict new point with KNN"""

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(data,classes)
new_class=knn.predict([(new_x,new_y)])
print(f"The new point belongs to class {new_class[0]}")
plt.scatter(x+[new_x],y+[new_y],c=classes+[int(new_class[0])])
plt.text(new_x,new_y-0.4,s=f"new point:class={new_class[0]}")
plt.show()

# Dataset source: https://archive.ics.uci.edu/dataset/292/wholesale+customers
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Wholesale customers data.csv')
df.head()

# Explore data
df.info()
df.isnull().sum()
df.nunique()
df.describe()

#Boxplot
plt.figure(figsize=(12,8))
cols=df.columns[2:]
sns.boxplot(data=df[cols])
plt.show()

# Remove outliers top largest 3 items
cols=['Fresh','Milk','Grocery','Frozen','Detergents_Paper','Delicassen']
for col in cols:
  df.drop(df[col].nlargest(3).index,inplace=True)
df.describe()

# Elbow method in real data
inertia_sale=[]
for i in range(1,16):
  kmeans=KMeans(n_clusters=i)
  kmeans.fit(df[cols])
  inertia_sale.append(kmeans.inertia_)
plt.plot(range(1,16),inertia_sale,marker='o')
plt.show()

# FIND OPTIMAL K AUTOMATICALLY
diff=np.diff(inertia_sale)
second_diff=np.diff(diff)
k_optimal=np.argmin(second_diff)+1
print(f"The Optimal value of k is: {k_optimal}")

# Find clustering plot
kmeans=KMeans(n_clusters=k_optimal)
kmeans.fit(df[cols])
classes=[int(c) for c in kmeans.labels_]
plt.scatter(df.Milk,df.Grocery,c=classes)
plt.xlabel('Milk')
plt.ylabel('Grocery')
plt.title('K-Means Clustering')
plt.show()

df.query('Fresh==112151')

df.query('Milk==73498')

df.query('Grocery==92780')

